# Sumstat config
exclude_MHC: 'b38' # Whether to exclude the MHC from analyses ['b37'|'b38']
min_cases: 100 # Minimum number of cases
min_maf:   0.005  # Min minor allele freq

# Distance based clumping
clump_dist: 250

# GCTA cojo select parameters [not used. Distance-based clumping only]
cojo_colin: 0.9   # Don't include SNPs that are colinear with an already selected SNP
cojo_wind:  2000   # (Kb) Assume SNPs outside window are in linkage equilibrium

# Finemapping parameters [not used]
fm_wind: 500   # (Kb) Window around the index on which to perform credible set analysis

# Credible set analysis [not used]
pp_threshold: 0.001 # Keep any variant which is in ((95% OR 99% credible set) AND post_posterior > pp_threshold)